# Generated by Django 4.1.7 on 2023-08-14 13:42

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgURL', models.ImageField(upload_to='images/')),
                ('cost', models.IntegerField(validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Card',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'ContactUs',
                'verbose_name_plural': 'ContactUs',
            },
        ),
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Balloons', 'Balloons'), ('Flowers', 'Flowers'), ('Stands', 'Stands'), ('Tables', 'Tables')], default='Flowers', max_length=20)),
                ('imgURL', models.URLField(max_length=400, null=True)),
                ('cost', models.IntegerField(validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
            ],
            options={
                'verbose_name': 'Decoration',
                'verbose_name_plural': 'Decoration',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Event',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Gallery',
            },
        ),
        migrations.CreateModel(
            name='HomePageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Home Page Gallery',
                'verbose_name_plural': 'Home Page Gallery',
            },
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Please enter phone number in the format: '+963 999999999'. Up to 9 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('instagram_profile', models.URLField()),
                ('facebook_profile', models.URLField()),
                ('image', models.ImageField(upload_to='')),
                ('sessionPrice', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, help_text='Session Description', max_length=400, null=True)),
            ],
            options={
                'verbose_name': 'Photographer',
                'verbose_name_plural': 'Photographer',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('crew', models.BooleanField(default=False)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('period', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cost', models.IntegerField(validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('eventID', models.ManyToManyField(to='EventsApp.event')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Place',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageName', models.CharField(choices=[('Wedding Package', 'Wedding Package'), ('Birthday Package', 'Birthday Package'), ('Party Package', 'Party Package'), ('Graduation Package', 'Graduation Package'), ('Baptism Package', 'Baptism Package'), ('Baby Gender Package ', 'Baby Gender Package ')], max_length=100)),
                ('img', models.ImageField(null=True, upload_to='')),
                ('cost', models.IntegerField(validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('Main_Dish', models.CharField(blank=True, max_length=200, null=True)),
                ('Drinks', models.CharField(blank=True, max_length=200, null=True)),
                ('Entrees', models.CharField(blank=True, max_length=200, null=True)),
                ('Desserts', models.CharField(blank=True, max_length=200, null=True)),
                ('eventID', models.ManyToManyField(to='EventsApp.event')),
            ],
            options={
                'verbose_name': 'Food',
                'verbose_name_plural': 'Food',
            },
        ),
        migrations.CreateModel(
            name='FinalReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=30)),
                ('date', models.DateField(default=datetime.date.today, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date.today)])),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('num_of_guests', models.IntegerField(default=0)),
                ('num_of_tables', models.IntegerField(default=0)),
                ('crew', models.BooleanField(null=True)),
                ('number_of_cards', models.IntegerField()),
                ('card_text', models.CharField(max_length=255)),
                ('customer_number', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('total_price', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000000000), django.core.validators.MinValueValidator(0)])),
                ('message', models.TextField(blank=True, max_length=400, null=True)),
                ('balloon_decoration', models.ForeignKey(blank=True, limit_choices_to={'category': 'Balloons'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balloon_decoration', to='EventsApp.decoration')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsApp.card')),
                ('flower_decoration', models.ForeignKey(blank=True, limit_choices_to={'category': 'Flowers'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flower_decoration', to='EventsApp.decoration')),
                ('food_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EventsApp.food')),
                ('photographer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EventsApp.photographer')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsApp.place')),
                ('stand_decoration', models.ForeignKey(blank=True, limit_choices_to={'category': 'Stands'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stand_decoration', to='EventsApp.decoration')),
                ('table_decoration', models.ForeignKey(blank=True, limit_choices_to={'category': 'Tables'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_decoration', to='EventsApp.decoration')),
            ],
            options={
                'verbose_name': 'Final Reservation',
                'verbose_name_plural': 'Final Reservation',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='eventID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsApp.event'),
        ),
    ]
